Feature/firebase login operations
burakkoc5/asset_tracker pull request #3
Opened 2024-12-20 00:07 UTC by burakkoc5

Firebase authentication setup for signin, signup.
A login button that triggers the signin operation.
On success, the user is redirected to the home page.
On failure, an error message is displayed.
State management has been implemented to manage login states with Bloc.
Minor UI adjustments, such as button styling changes.

2024-12-20 09:42 UTC, E-MRE requested changes
Güzel olmuş, önemli dosyaları gizlersen çok daha iyi olacak

2024-12-20 09:42 UTC, E-MRE commented on android/app/google-services.json
> +{
gitignore ile bu dosyayı gizlemekte yarar var. dışarıdan görünmesi güvenlik açısından tehlike

2024-12-20 09:42 UTC, E-MRE commented on firebase.json
> +{"flutter":{"platforms":{"android":{"default":{"projectId":"asset-tracker-3cc21","appId":"1:490137200342:android:52806d2e5cffbb33210b77","fileOutput":"android/app/google-services.json"}},"ios":{"defa
bunu da gizleyebiliriz.

2024-12-20 09:42 UTC, E-MRE commented on lib/firebase_options.dart
> +class DefaultFirebaseOptions {
bu dosya da gizlenebilir

2024-12-21 11:27 UTC, E-MRE approved these changes
Eline sağlık

2024-12-21 11:27 UTC, E-MRE commented on lib/core/widgets/container_button.dart
> +                EdgeInsets.only(left: isBig ? 16 : 8, right: isBig ? 16 : 4),
sizes

2024-12-21 11:27 UTC, E-MRE commented on lib/main.dart
> +  await Firebase.initializeApp(
appInıt

2024-12-21 11:27 UTC, E-MRE commented on lib/main.dart
> +    BlocProvider<AuthenticationCubit>(
multi provider

2024-12-22 15:25 UTC, burakkoc5 commented
### Merge Request: Authentication & Firebase Enhancements  

- **Firebase Integration:**  
  - Configured Firebase for Android/iOS.  
  - Added and later removed sensitive Firebase files from version control.  
  - Created `FirebaseAuthException` extension for error handling.  

- **Authentication Features:**  
  - Implemented sign-in, sign-up, and sign-out functionality.  
  - Integrated `AuthCubit` for state management during registration.  

- **UI Enhancements:**  
  - Fixed overflow issue on registration forms with a scrollable view.  
  - Added ripple effect for button interactions.  

- **Localization:**  
  - Added translations for all user-facing strings.  

- **Codebase Improvements:**  
  - Updated `.gitignore` to exclude sensitive files.  
  - Integrated `GetIt` for service locator pattern.  
  - Edited folder structure for better organization.  

- **Bug Fixes:**  
  - Addressed minor UI and functionality issues.  
  - Cleaned up and secured version control files.

2024-12-22 15:25 UTC, merged